# Generated by Django 5.2.4 on 2025-08-02 04:19

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='RdPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('hero', 1), ('intro_text', 3), ('image_text', 5), ('icon_grid', 8)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.StructBlock', [[('image', 0)]], {}), 2: ('wagtail.blocks.CharBlock', (), {}), 3: ('wagtail.blocks.StructBlock', [[('title', 2)]], {}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Image on Left'), ('right', 'Image on Right')], 'label': 'Image Alignment'}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 2), ('image_alignment', 4)]], {}), 6: ('wagtail.blocks.StructBlock', [[('icon', 0), ('title', 2)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {}), 8: ('wagtail.blocks.StructBlock', [[('cards', 7)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
