# Generated by Django 5.2.4 on 2025-08-06 04:01

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rd_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdpage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 1), ('intro_text', 4), ('image_text', 6), ('icon_grid', 9)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.StructBlock', [[('image', 0)]], {}), 2: ('wagtail.blocks.CharBlock', (), {}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link']}), 4: ('wagtail.blocks.StructBlock', [[('title', 2), ('text', 3)]], {}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Image on Left'), ('right', 'Image on Right')], 'label': 'Image Alignment'}), 6: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 2), ('text', 3), ('image_alignment', 5)]], {}), 7: ('wagtail.blocks.StructBlock', [[('icon', 0), ('title', 2), ('text', 3)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {}), 9: ('wagtail.blocks.StructBlock', [[('cards', 8)]], {})}),
        ),
    ]
