# Generated by Django 5.2.4 on 2025-08-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_applicationsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Career Submission',
                'verbose_name_plural': 'Career Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
