# Generated by Django 5.2.4 on 2025-08-07 09:30

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('hero', 6), ('learning_tabs', 10), ('stats_banner', 13), ('program_info', 14), ('providers_video', 20), ('contact_banner', 21)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.blocks.RichTextBlock', (), {}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Certification Logo'}), 4: ('wagtail.blocks.ListBlock', (3,), {}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'Apply Now'}), 6: ('wagtail.blocks.StructBlock', [[('image', 0), ('tag', 1), ('title', 1), ('description', 2), ('duration', 1), ('mode', 1), ('certifications', 4), ('apply_button_text', 5)]], {}), 7: ('wagtail.blocks.RichTextBlock', (), {'features': ['ul'], 'help_text': 'Use a bulleted list for the content.'}), 8: ('wagtail.blocks.StructBlock', [[('tab_title', 1), ('tab_subtitle', 1), ('content_list', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {}), 10: ('wagtail.blocks.StructBlock', [[('tabs', 9)]], {}), 11: ('wagtail.blocks.StructBlock', [[('value', 1), ('label', 1)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {}), 13: ('wagtail.blocks.StructBlock', [[('title', 1), ('subtitle', 1), ('stats', 12)]], {}), 14: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'label': 'Program Info / Text Section', 'template': 'blocks/course_page/rich_text_block.html'}), 15: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Provider Logo'}), 16: ('wagtail.blocks.ListBlock', (15,), {}), 17: ('wagtail.blocks.URLBlock', (), {}), 18: ('wagtail.blocks.CharBlock', (), {'default': 'Enquire Now'}), 19: ('wagtail.blocks.CharBlock', (), {'default': 'Download Brochure'}), 20: ('wagtail.blocks.StructBlock', [[('title', 1), ('subtitle', 1), ('logos', 16), ('video_thumbnail', 0), ('video_url', 17), ('enquire_button_text', 18), ('brochure_button_text', 19)]], {}), 21: ('wagtail.blocks.StructBlock', [[]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
