# Generated by Django 5.2.4 on 2025-08-08 14:21

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_coursepage_body'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 7), ('learning_tabs', 11), ('stats_banner', 14), ('program_info', 16), ('providers_video', 23), ('contact_banner', 25)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Certification Logo'}), 4: ('wagtail.blocks.ListBlock', (3,), {'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'Apply Now', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 20, 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('image', 0), ('tag', 1), ('title', 1), ('description', 2), ('duration', 1), ('mode', 1), ('certifications', 4), ('apply_button_text', 5), ('phone_number', 6)]], {}), 8: ('wagtail.blocks.RichTextBlock', (), {'features': ['ul'], 'help_text': 'Use a bulleted list.', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('tab_title', 1), ('tab_subtitle', 1), ('content_list', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {'required': False}), 11: ('wagtail.blocks.StructBlock', [[('tabs', 10)]], {}), 12: ('wagtail.blocks.StructBlock', [[('value', 1), ('label', 1)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {'required': False}), 14: ('wagtail.blocks.StructBlock', [[('title', 1), ('subtitle', 1), ('stats', 13)]], {}), 15: ('wagtail.blocks.RichTextBlock', (), {}), 16: ('wagtail.blocks.StructBlock', [[('subtitle', 1), ('title', 1), ('text', 15)]], {'icon': 'pilcrow', 'label': 'Program Info Section', 'template': 'blocks/course_page/program_info_block.html'}), 17: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Provider Logo'}), 18: ('wagtail.blocks.ListBlock', (17,), {'required': False}), 19: ('wagtail.blocks.URLBlock', (), {'required': False}), 20: ('wagtail.blocks.CharBlock', (), {'default': 'Enquire Now', 'required': False}), 21: ('wagtail.blocks.CharBlock', (), {'default': 'Download Brochure', 'required': False}), 22: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': False}), 23: ('wagtail.blocks.StructBlock', [[('title', 1), ('subtitle', 1), ('logos', 18), ('video_thumbnail', 0), ('video_url', 19), ('enquire_button_text', 20), ('brochure_button_text', 21), ('brochure_file', 22)]], {}), 24: ('wagtail.blocks.EmailBlock', (), {'required': False}), 25: ('wagtail.blocks.StructBlock', [[('contact_one_flag', 0), ('contact_one_phone', 6), ('contact_one_email', 24), ('contact_two_flag', 0), ('contact_two_phone', 6), ('contact_two_email', 24)]], {})}),
        ),
        migrations.CreateModel(
            name='CourseAccreditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('text', models.CharField(max_length=100)),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='accreditations', to='courses.coursepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
