# Generated by Django 5.2.4 on 2025-08-14 09:59

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_coursepage_body'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('hero', 2), ('learning_points', 7), ('at_a_glance', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': False}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('logo', 1), ('duration', 0), ('payment_terms', 0), ('tax_info', 0)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'What You Will Learn', 'required': False}), 4: ('wagtail.blocks.RichTextBlock', (), {'features': ['ul'], 'help_text': 'Use a bulleted list for points.'}), 5: ('wagtail.blocks.StructBlock', [[('points', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {'label': 'Point Column'}), 7: ('wagtail.blocks.StructBlock', [[('title', 3), ('columns', 6)]], {}), 8: ('wagtail.blocks.StructBlock', [[('icon', 1), ('label', 0), ('value', 0)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {}), 10: ('wagtail.blocks.StructBlock', [[('tag', 0), ('title', 0), ('subtitle', 0), ('items', 9)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 7), ('learning_tabs', 11), ('stats_banner', 14), ('program_info', 15), ('providers_video', 23), ('contact_banner', 25), ('certifications_grid', 31), ('training_details', 34), ('locations', 40)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Certification Logo', 'required': False}), 4: ('wagtail.blocks.ListBlock', (3,), {'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'Apply Now', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 20, 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('image', 0), ('tag', 1), ('title', 1), ('description', 2), ('duration', 1), ('mode', 1), ('eligibility', 1), ('certifications', 4), ('apply_button_text', 5), ('phone_number', 6)]], {}), 8: ('wagtail.blocks.RichTextBlock', (), {'features': ['ul'], 'help_text': 'Use a bulleted list.', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('tab_title', 1), ('tab_subtitle', 1), ('content_list', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {'required': False}), 11: ('wagtail.blocks.StructBlock', [[('tabs', 10)]], {}), 12: ('wagtail.blocks.StructBlock', [[('value', 1), ('label', 1)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {'required': False}), 14: ('wagtail.blocks.StructBlock', [[('title', 1), ('subtitle', 1), ('stats', 13)]], {}), 15: ('wagtail.blocks.StructBlock', [[('title', 1), ('subtitle', 1), ('text', 2)]], {'icon': 'pilcrow', 'label': 'Program Info Section', 'template': 'blocks/course_page/program_info_block.html'}), 16: ('wagtail.blocks.CharBlock', (), {'label': 'Main Section Title', 'required': False}), 17: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Provider Logo', 'required': False}), 18: ('wagtail.blocks.ListBlock', (17,), {'required': False}), 19: ('wagtail.blocks.URLBlock', (), {'required': False}), 20: ('wagtail.blocks.CharBlock', (), {'default': 'Enquire Now', 'required': False}), 21: ('wagtail.blocks.CharBlock', (), {'default': 'Download Brochure', 'required': False}), 22: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': False}), 23: ('wagtail.blocks.StructBlock', [[('main_title', 16), ('title', 1), ('subtitle', 1), ('logos', 18), ('video_thumbnail', 0), ('video_url', 19), ('enquire_button_text', 20), ('brochure_button_text', 21), ('brochure_file', 22)]], {}), 24: ('wagtail.blocks.EmailBlock', (), {'required': False}), 25: ('wagtail.blocks.StructBlock', [[('contact_one_flag', 0), ('contact_one_phone', 6), ('contact_one_email', 24), ('contact_two_flag', 0), ('contact_two_phone', 6), ('contact_two_email', 24)]], {}), 26: ('wagtail.blocks.CharBlock', (), {'default': 'Courses / Certifications', 'required': False}), 27: ('wagtail.blocks.CharBlock', (), {'default': 'Know More', 'required': False}), 28: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 29: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('button_text', 27), ('button_link', 28)]], {}), 30: ('wagtail.blocks.ListBlock', (29,), {'required': False}), 31: ('wagtail.blocks.StructBlock', [[('title', 26), ('cards', 30)]], {}), 32: ('wagtail.blocks.RichTextBlock', (), {'features': ['ul'], 'label': 'Detail Item', 'required': False}), 33: ('wagtail.blocks.ListBlock', (32,), {'required': False}), 34: ('wagtail.blocks.StructBlock', [[('main_logo', 0), ('main_title', 1), ('left_column_title', 1), ('left_column_items', 33), ('middle_column_title', 1), ('middle_column_items', 33), ('right_column_title', 1), ('right_column_items', 33)]], {}), 35: ('wagtail.blocks.CharBlock', (), {'default': 'VISIT US', 'required': False}), 36: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g., CALICUT, INDIA', 'required': False}), 37: ('wagtail.blocks.CharBlock', (), {'default': 'TECHNO DOT ACADEMY', 'required': False}), 38: ('wagtail.blocks.StructBlock', [[('icon', 0), ('location_name', 36), ('office_name', 37), ('address', 2), ('phone', 1), ('email', 24)]], {}), 39: ('wagtail.blocks.ListBlock', (38,), {}), 40: ('wagtail.blocks.StructBlock', [[('title', 35), ('locations', 39)]], {})}),
        ),
    ]
