# Generated by Django 5.2.4 on 2025-08-14 10:34

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_communitypage_alter_coursepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 2), ('learning_points', 5), ('at_a_glance', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': False}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('logo', 1), ('duration', 0), ('payment_terms', 0), ('tax_info', 0)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'What You Will Learn', 'required': False}), 4: ('wagtail.blocks.RichTextBlock', (), {'features': ['ul'], 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 3), ('left_column_title', 0), ('left_column_subtitle', 0), ('left_column_points', 4), ('right_column_title', 0), ('right_column_subtitle', 0), ('right_column_points', 4)]], {}), 6: ('wagtail.blocks.StructBlock', [[('icon', 1), ('label', 0), ('value', 0)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {}), 8: ('wagtail.blocks.StructBlock', [[('tag', 0), ('title', 0), ('subtitle', 0), ('items', 7)]], {})}),
        ),
    ]
