# Generated by Django 5.2.4 on 2025-08-14 11:41

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_communitypage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 2), ('learning_points', 9), ('at_a_glance', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': False}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('logo', 1), ('duration', 0), ('payment_terms', 0), ('tax_info', 0)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'What You Will Learn', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {}), 5: ('wagtail.blocks.StructBlock', [[('title', 4), ('subtitle', 0)]], {}), 6: ('wagtail.blocks.RichTextBlock', (), {'features': ['ul']}), 7: ('wagtail.blocks.StructBlock', [[('points', 6)]], {}), 8: ('wagtail.blocks.StreamBlock', [[('column_title', 5), ('bullet_list', 7)]], {'use_json_field': True}), 9: ('wagtail.blocks.StructBlock', [[('title', 3), ('body', 8)]], {}), 10: ('wagtail.blocks.StructBlock', [[('icon', 1), ('label', 0), ('value', 0)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {}), 12: ('wagtail.blocks.StructBlock', [[('tag', 0), ('title', 0), ('subtitle', 0), ('items', 11)]], {})}),
        ),
    ]
