# Generated by Django 5.2.4 on 2025-08-14 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_communitypage_body'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommunityPage',
        ),
    ]
