# Generated by Django 5.2.4 on 2025-07-28 09:28

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero_cards', 4), ('features_section', 11), ('courses_section', 19), ('cta_section', 23)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Add an emoji or icon character. e.g. 💻, 🚀, 📊', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'max_length': 200, 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('icon', 0), ('title', 1), ('description', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {'label': 'Floating Cards (Hero Section)'}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'Why Choose Our Platform?'}), 6: ('wagtail.blocks.TextBlock', (), {'default': 'Experience the future of education...'}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Add an emoji or icon character. e.g. 🎯, 🏭, 🤝', 'required': True}), 8: ('wagtail.blocks.TextBlock', (), {'max_length': 255, 'required': True}), 9: ('wagtail.blocks.StructBlock', [[('icon', 7), ('title', 1), ('description', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.StructBlock', [[('title', 5), ('subtitle', 6), ('features', 10)]], {'icon': 'cogs', 'label': 'Features Section', 'template': 'blocks/features_section.html'}), 12: ('wagtail.blocks.CharBlock', (), {'default': 'Featured Courses'}), 13: ('wagtail.blocks.TextBlock', (), {'default': "Cutting-edge programs for tomorrow's professionals"}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'Add an emoji or icon character. e.g. ☁️, 🌐, 📱', 'required': True}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': 'Comma-separated tags, e.g., Popular, Cloud', 'required': False}), 16: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': True}), 17: ('wagtail.blocks.StructBlock', [[('icon', 14), ('tags', 15), ('title', 1), ('description', 8), ('duration', 1), ('price', 16)]], {}), 18: ('wagtail.blocks.ListBlock', (17,), {}), 19: ('wagtail.blocks.StructBlock', [[('title', 12), ('subtitle', 13), ('courses', 18)]], {'icon': 'folder-open-inverse', 'label': 'Courses Section', 'template': 'blocks/courses_section.html'}), 20: ('wagtail.blocks.CharBlock', (), {'default': 'Ready to Start Your Journey?'}), 21: ('wagtail.blocks.TextBlock', (), {'default': 'Enroll today and unlock your potential.'}), 22: ('wagtail.blocks.CharBlock', (), {'default': 'Enroll Now'}), 23: ('wagtail.blocks.StructBlock', [[('title', 20), ('description', 21), ('button_text', 22)]], {'icon': 'plus-inverse', 'label': 'Call to Action', 'template': 'blocks/cta_section.html'})}, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_primary_button_text',
            field=models.CharField(default='Explore Courses', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_secondary_button_text',
            field=models.CharField(default='Live Demo', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(blank=True, help_text='The main heading. Use <span>...</span> for gradient text.', max_length=255),
        ),
    ]
