# Generated by Django 5.2.4 on 2025-07-29 06:55

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepagestat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero_cards', 4), ('features_section', 11), ('partners_section', 17), ('courses_section', 25), ('cta_section', 29)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Add an emoji or icon character. e.g. 💻, 🚀, 📊', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'max_length': 200, 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('icon', 0), ('title', 1), ('description', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {'label': 'Floating Cards (Hero Section)'}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'Why Choose Our Platform?'}), 6: ('wagtail.blocks.TextBlock', (), {'default': 'Experience the future of education...'}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Add an emoji or icon character. e.g. 🎯, 🏭, 🤝', 'required': True}), 8: ('wagtail.blocks.TextBlock', (), {'max_length': 255, 'required': True}), 9: ('wagtail.blocks.StructBlock', [[('icon', 7), ('title', 1), ('description', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.StructBlock', [[('title', 5), ('subtitle', 6), ('features', 10)]], {'icon': 'cogs', 'label': 'Features Section', 'template': 'blocks/features_section.html'}), 12: ('wagtail.blocks.CharBlock', (), {'default': 'Partnerships and Certifications'}), 13: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'For alt text and internal reference', 'required': True}), 15: ('wagtail.blocks.StructBlock', [[('logo_image', 13), ('partner_name', 14)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {}), 17: ('wagtail.blocks.StructBlock', [[('title', 12), ('logos', 16)]], {'icon': 'group', 'label': 'Partners Section', 'template': 'blocks/partners_section.html'}), 18: ('wagtail.blocks.CharBlock', (), {'default': 'Featured Courses'}), 19: ('wagtail.blocks.TextBlock', (), {'default': "Cutting-edge programs for tomorrow's professionals"}), 20: ('wagtail.blocks.CharBlock', (), {'help_text': 'Add an emoji or icon character. e.g. ☁️, 🌐, 📱', 'required': True}), 21: ('wagtail.blocks.CharBlock', (), {'help_text': 'Comma-separated tags, e.g., Popular, Cloud', 'required': False}), 22: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': True}), 23: ('wagtail.blocks.StructBlock', [[('icon', 20), ('tags', 21), ('title', 1), ('description', 8), ('duration', 1), ('price', 22)]], {}), 24: ('wagtail.blocks.ListBlock', (23,), {}), 25: ('wagtail.blocks.StructBlock', [[('title', 18), ('subtitle', 19), ('courses', 24)]], {'icon': 'folder-open-inverse', 'label': 'Courses Section', 'template': 'blocks/courses_section.html'}), 26: ('wagtail.blocks.CharBlock', (), {'default': 'Ready to Start Your Journey?'}), 27: ('wagtail.blocks.TextBlock', (), {'default': 'Enroll today and unlock your potential.'}), 28: ('wagtail.blocks.CharBlock', (), {'default': 'Enroll Now'}), 29: ('wagtail.blocks.StructBlock', [[('title', 26), ('description', 27), ('button_text', 28)]], {'icon': 'plus-inverse', 'label': 'Call to Action', 'template': 'blocks/cta_section.html'})}, null=True),
        ),
    ]
