# Generated by Django 5.2.4 on 2025-07-30 04:42

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_homepage_body'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero_cards', 4), ('features_section', 11), ('solutions_section', 19), ('partners_section', 24), ('testimonials_section', 30), ('courses_section', 38), ('contact_form', 42), ('cta_section', 46)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Add an emoji or icon character. e.g. 💻, 🚀, 📊', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'max_length': 200, 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('icon', 0), ('title', 1), ('description', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {'label': 'Floating Cards (Hero Section)'}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'Why Choose Our Platform?'}), 6: ('wagtail.blocks.TextBlock', (), {'default': 'Experience the future of education...'}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Add an emoji or icon character. e.g. 🎯, 🏭, 🤝', 'required': True}), 8: ('wagtail.blocks.TextBlock', (), {'max_length': 255, 'required': True}), 9: ('wagtail.blocks.StructBlock', [[('icon', 7), ('title', 1), ('description', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.StructBlock', [[('title', 5), ('subtitle', 6), ('features', 10)]], {'icon': 'cogs', 'label': 'Features Section', 'template': 'blocks/features_section.html'}), 12: ('wagtail.blocks.CharBlock', (), {'default': 'THE IDEAL SOLUTION FOR YOUR BUSINESS'}), 13: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 14: ('wagtail.blocks.CharBlock', (), {'required': True}), 15: ('wagtail.blocks.TextBlock', (), {'required': True}), 16: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 17: ('wagtail.blocks.StructBlock', [[('image', 13), ('title', 14), ('text', 15), ('link_page', 16)]], {}), 18: ('wagtail.blocks.ListBlock', (17,), {}), 19: ('wagtail.blocks.StructBlock', [[('title', 12), ('solutions', 18)]], {'icon': 'list-ul', 'label': 'Solutions Section', 'template': 'blocks/solutions_section.html'}), 20: ('wagtail.blocks.CharBlock', (), {'default': 'Partnerships and Certifications'}), 21: ('wagtail.blocks.CharBlock', (), {'help_text': 'For alt text and internal reference', 'required': True}), 22: ('wagtail.blocks.StructBlock', [[('logo_image', 13), ('partner_name', 21)]], {}), 23: ('wagtail.blocks.ListBlock', (22,), {}), 24: ('wagtail.blocks.StructBlock', [[('title', 20), ('logos', 23)]], {'icon': 'group', 'label': 'Partners Section', 'template': 'blocks/partners_section.html'}), 25: ('wagtail.blocks.CharBlock', (), {'default': 'TESTIMONIALS'}), 26: ('wagtail.blocks.TextBlock', (), {'help_text': "The person's testimonial.", 'required': True}), 27: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g., Digital Finance or Kerala, India', 'required': False}), 28: ('wagtail.blocks.StructBlock', [[('image', 13), ('quote', 26), ('author_name', 14), ('author_role', 27)]], {}), 29: ('wagtail.blocks.ListBlock', (28,), {}), 30: ('wagtail.blocks.StructBlock', [[('title', 25), ('testimonials', 29)]], {'icon': 'group', 'label': 'Testimonials Section', 'template': 'blocks/testimonials_section.html'}), 31: ('wagtail.blocks.CharBlock', (), {'default': 'Featured Courses'}), 32: ('wagtail.blocks.TextBlock', (), {'default': "Cutting-edge programs for tomorrow's professionals"}), 33: ('wagtail.blocks.CharBlock', (), {'help_text': 'Add an emoji or icon character. e.g. ☁️, 🌐, 📱', 'required': True}), 34: ('wagtail.blocks.CharBlock', (), {'help_text': 'Comma-separated tags, e.g., Popular, Cloud', 'required': False}), 35: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': True}), 36: ('wagtail.blocks.StructBlock', [[('icon', 33), ('tags', 34), ('title', 1), ('description', 8), ('duration', 1), ('price', 35)]], {}), 37: ('wagtail.blocks.ListBlock', (36,), {}), 38: ('wagtail.blocks.StructBlock', [[('title', 31), ('subtitle', 32), ('courses', 37)]], {'icon': 'folder-open-inverse', 'label': 'Courses Section', 'template': 'blocks/courses_section.html'}), 39: ('wagtail.blocks.CharBlock', (), {'default': 'Get In Touch With Us!'}), 40: ('wagtail.blocks.RichTextBlock', (), {}), 41: ('wagtail.blocks.CharBlock', (), {'default': 'QUICK CONTACT'}), 42: ('wagtail.blocks.StructBlock', [[('left_column_title', 39), ('left_column_text', 40), ('form_title', 41)]], {}), 43: ('wagtail.blocks.CharBlock', (), {'default': 'Ready to Start Your Journey?'}), 44: ('wagtail.blocks.TextBlock', (), {'default': 'Enroll today and unlock your potential.'}), 45: ('wagtail.blocks.CharBlock', (), {'default': 'Enroll Now'}), 46: ('wagtail.blocks.StructBlock', [[('title', 43), ('description', 44), ('button_text', 45)]], {'icon': 'plus-inverse', 'label': 'Call to Action', 'template': 'blocks/cta_section.html'})}, null=True),
        ),
    ]
