# Generated by Django 5.2.4 on 2025-07-30 05:56

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_standardpage_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardpage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 2), ('two_columns', 6), ('centered_text_image', 7), ('full_width_cta', 8), ('icon_grid', 11)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Add <strong> tags for bold text'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('image', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Use <br> for line breaks'}), 4: ('wagtail.blocks.CharBlock', (), {}), 5: ('wagtail.blocks.RichTextBlock', (), {}), 6: ('wagtail.blocks.StructBlock', [[('left_column_title', 3), ('right_column_title', 4), ('right_column_text', 5)]], {}), 7: ('wagtail.blocks.StructBlock', [[('title', 4), ('text', 5), ('image', 1)]], {}), 8: ('wagtail.blocks.StructBlock', [[('title', 3), ('text', 5)]], {}), 9: ('wagtail.blocks.StructBlock', [[('icon', 1), ('title', 3), ('text', 5)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.StructBlock', [[('title', 4), ('cards', 10)]], {})}),
        ),
    ]
