# Generated by Django 5.2.4 on 2025-08-02 11:08

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_recruitmentpage_alter_homepage_body_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('hero', 2), ('intro', 3), ('main_content', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Use <br> for line breaks'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('image', 1)]], {}), 3: ('wagtail.blocks.StructBlock', [[]], {}), 4: ('wagtail.blocks.CharBlock', (), {}), 5: ('wagtail.blocks.StructBlock', [[('icon', 1), ('title', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {}), 7: ('wagtail.blocks.StructBlock', [[('background_image', 1), ('services', 6)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero_cards', 4), ('features_section', 11), ('solutions_section', 18), ('tabbed_content', 27), ('partners_section', 31), ('testimonials_section', 36), ('courses_section', 42), ('contact_form', 46), ('cta_section', 47)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Add an emoji or icon character. e.g. 💻, 🚀, 📊', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'max_length': 200, 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('icon', 0), ('title', 1), ('description', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {}), 5: ('wagtail.blocks.CharBlock', (), {}), 6: ('wagtail.blocks.TextBlock', (), {}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Add an emoji or icon character. e.g. 🎯, 🏭, 🤝', 'required': True}), 8: ('wagtail.blocks.TextBlock', (), {'max_length': 255, 'required': True}), 9: ('wagtail.blocks.StructBlock', [[('icon', 7), ('title', 1), ('description', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {}), 11: ('wagtail.blocks.StructBlock', [[('title', 5), ('subtitle', 6), ('features', 10)]], {'template': 'blocks/features_section.html'}), 12: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 13: ('wagtail.blocks.CharBlock', (), {'required': True}), 14: ('wagtail.blocks.TextBlock', (), {'required': True}), 15: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 16: ('wagtail.blocks.StructBlock', [[('image', 12), ('title', 13), ('text', 14), ('link_page', 15)]], {}), 17: ('wagtail.blocks.ListBlock', (16,), {}), 18: ('wagtail.blocks.StructBlock', [[('title', 5), ('solutions', 17)]], {'template': 'blocks/solutions_section.html'}), 19: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 20: ('wagtail.blocks.CharBlock', (), {'required': False}), 21: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 22: ('wagtail.blocks.CharBlock', (), {'default': 'Explore'}), 23: ('wagtail.blocks.StructBlock', [[('header_title', 5), ('header_subtitle', 20), ('icon', 21), ('text', 6), ('button_text', 22), ('button_link', 15)]], {}), 24: ('wagtail.blocks.ListBlock', (23,), {}), 25: ('wagtail.blocks.StructBlock', [[('tab_title', 5), ('tab_icon', 19), ('cards', 24)]], {}), 26: ('wagtail.blocks.ListBlock', (25,), {}), 27: ('wagtail.blocks.StructBlock', [[('tabs', 26)]], {}), 28: ('wagtail.blocks.CharBlock', (), {'help_text': 'For alt text and internal reference', 'required': True}), 29: ('wagtail.blocks.StructBlock', [[('logo_image', 12), ('partner_name', 28)]], {}), 30: ('wagtail.blocks.ListBlock', (29,), {}), 31: ('wagtail.blocks.StructBlock', [[('title', 5), ('logos', 30)]], {'template': 'blocks/partners_section.html'}), 32: ('wagtail.blocks.TextBlock', (), {'help_text': "The person's testimonial.", 'required': True}), 33: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g., Digital Finance or Kerala, India', 'required': False}), 34: ('wagtail.blocks.StructBlock', [[('image', 12), ('quote', 32), ('author_name', 13), ('author_role', 33)]], {}), 35: ('wagtail.blocks.ListBlock', (34,), {}), 36: ('wagtail.blocks.StructBlock', [[('title', 5), ('testimonials', 35)]], {'template': 'blocks/testimonials_section.html'}), 37: ('wagtail.blocks.CharBlock', (), {'help_text': 'Add an emoji or icon character. e.g. ☁️, 🌐, 📱', 'required': True}), 38: ('wagtail.blocks.CharBlock', (), {'help_text': 'Comma-separated tags, e.g., Popular, Cloud', 'required': False}), 39: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': True}), 40: ('wagtail.blocks.StructBlock', [[('icon', 37), ('tags', 38), ('title', 1), ('description', 8), ('duration', 1), ('price', 39)]], {}), 41: ('wagtail.blocks.ListBlock', (40,), {}), 42: ('wagtail.blocks.StructBlock', [[('title', 5), ('subtitle', 6), ('courses', 41)]], {'template': 'blocks/courses_section.html'}), 43: ('wagtail.blocks.CharBlock', (), {'default': 'Get In Touch With Us!'}), 44: ('wagtail.blocks.RichTextBlock', (), {}), 45: ('wagtail.blocks.CharBlock', (), {'default': 'QUICK CONTACT'}), 46: ('wagtail.blocks.StructBlock', [[('left_column_title', 43), ('left_column_text', 44), ('form_title', 45)]], {}), 47: ('wagtail.blocks.StructBlock', [[('title', 5), ('description', 6), ('button_text', 5)]], {'template': 'blocks/cta_section.html'})}, null=True),
        ),
    ]
