# Generated by Django 5.2.4 on 2025-08-10 08:53

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_consultingpage_body_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardpage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 2), ('two_columns', 6), ('centered_text_image', 7), ('full_width_cta', 8), ('icon_grid', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Add <strong> tags for bold text', 'required': False}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('image', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Use <br> for line breaks', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'required': False}), 5: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('left_column_title', 3), ('right_column_title', 4), ('right_column_text', 5)]], {}), 7: ('wagtail.blocks.StructBlock', [[('title', 4), ('text', 5), ('image', 1)]], {}), 8: ('wagtail.blocks.StructBlock', [[('title', 3), ('text', 5)]], {}), 9: ('wagtail.blocks.CharBlock', (), {}), 10: ('wagtail.blocks.StructBlock', [[('icon', 1), ('title', 3), ('text', 5)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {}), 12: ('wagtail.blocks.StructBlock', [[('title', 9), ('cards', 11)]], {})}),
        ),
    ]
