# Generated by Django 5.2.4 on 2025-08-12 04:29

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('placements', 5), ('careers_form', 9), ('open_positions', 16), ('photo_gallery', 20)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Placements', 'required': False}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('image', 1), ('name', 2), ('role', 2), ('company', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('students', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'default': 'CAREERS', 'required': False}), 7: ('wagtail.blocks.TextBlock', (), {'required': False}), 8: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'e.g., Please share your resume with hr@techno.academy', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('title', 6), ('subtitle', 7), ('email_info', 8)]], {}), 10: ('wagtail.blocks.CharBlock', (), {'default': 'OPEN POSITIONS', 'required': False}), 11: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': False}), 12: ('wagtail.blocks.URLBlock', (), {'required': False}), 13: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Check to make this position stand out with a dark background.', 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('title', 2), ('position_count', 11), ('apply_link', 12), ('is_highlighted', 13)]], {}), 15: ('wagtail.blocks.ListBlock', (14,), {'required': False}), 16: ('wagtail.blocks.StructBlock', [[('title', 10), ('positions', 15)]], {}), 17: ('wagtail.blocks.CharBlock', (), {'default': 'More Photos', 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('image', 1), ('label', 2), ('button_text', 17)]], {}), 19: ('wagtail.blocks.ListBlock', (18,), {'required': False}), 20: ('wagtail.blocks.StructBlock', [[('images', 19)]], {})})),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
