# Generated by Django 5.2.4 on 2025-08-12 07:27

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companypage',
            name='body',
            field=wagtail.fields.StreamField([('intro', 2), ('placements', 7), ('careers_form', 10), ('open_positions', 17), ('photo_gallery', 22)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': False}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Placements', 'required': False}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 4), ('name', 0), ('role', 0), ('company', 0)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('title', 3), ('students', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'default': 'CAREERS', 'required': False}), 9: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'e.g., Please share your resume with hr@techno.academy', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('title', 8), ('subtitle', 1), ('email_info', 9)]], {}), 11: ('wagtail.blocks.CharBlock', (), {'default': 'OPEN POSITIONS', 'required': False}), 12: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': False}), 13: ('wagtail.blocks.URLBlock', (), {'required': False}), 14: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Check to make this position stand out with a dark background.', 'required': False}), 15: ('wagtail.blocks.StructBlock', [[('title', 0), ('position_count', 12), ('apply_link', 13), ('is_highlighted', 14)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {'required': False}), 17: ('wagtail.blocks.StructBlock', [[('title', 11), ('positions', 16)]], {}), 18: ('wagtail.blocks.CharBlock', (), {'default': 'More Photos', 'required': False}), 19: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['company.GalleryPage'], 'required': False}), 20: ('wagtail.blocks.StructBlock', [[('image', 4), ('label', 0), ('button_text', 18), ('link_page', 19)]], {}), 21: ('wagtail.blocks.ListBlock', (20,), {'required': False}), 22: ('wagtail.blocks.StructBlock', [[('images', 21)]], {})}),
        ),
        migrations.CreateModel(
            name='GalleryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro_title', models.CharField(max_length=255)),
                ('tag', models.CharField(blank=True, max_length=100)),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='GalleryPageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='company.gallerypage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
