# Generated by Django 5.2.4 on 2025-08-13 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_prefilled_text',
            field=models.CharField(blank=True, help_text='Optional: The default message that will appear when a user clicks the button.', max_length=200),
        ),
    ]
