# Generated by Django 5.2.4 on 2025-08-20 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_sitesettings_whatsapp_prefilled_text'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='light_logo',
            field=models.ForeignKey(blank=True, help_text='The logo to display when light mode is active. Should be dark text on a transparent background.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
