# Generated by Django 5.2.4 on 2025-08-01 11:22

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebinarPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('title_override', models.CharField(blank=True, help_text='Optional. If blank, the page title will be used.', max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='WebinarCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('tag', models.CharField(default='FREE LIVE webinar session', max_length=100)),
                ('trainer_name', models.CharField(max_length=255)),
                ('trainer_role', models.CharField(max_length=255)),
                ('workshop_title', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('is_expired', models.BooleanField(default=False)),
                ('apply_link', models.URLField(blank=True)),
                ('trainer_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='webinar_cards', to='webinar.webinarpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
